version: '3.1'
services:
  django-tutorial:
    container_name: django-tutorial-ic
    image: oscarlucas/djangoic
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      HOST: bd_mariadb_django
      USER: django
      PASSWD: django
      DB: django
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.org
    ports:
      - 8100:8006
    depends_on:
      - db_django
  db_django:
    container_name: bd_mariadb_django-ic
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django
    volumes:
      - mariadb_data_django_ic:/var/lib/mysql
volumes:
    mariadb_data_django_ic:
